### ISSUE TITLE
Unhandled 'error' event on Meteor 0.8.2

### ISSUE THREAD

**Issue by stefanocudini** [sylvaingi/meteor-imagemagick#4]
I'm using this code for resize an image:

``` javascript

Meteor.methods({

    uploadAvatar: function(blob) {

        if(!this.userId) return null;

        var fs = Npm.require('fs'),
            path = Meteor.settings.dirs.avatars,
            username = Meteor.user().username,
            filename = username +'_'+ (new Date()).getTime();

        console.log('uploadAvatar: wrinting...', filename);
        fs.writeFileSync(path + filename+'.big.jpg', blob, 'binary');

        console.log('uploadAvatar: resizing...');
        Imagemagick.crop({
            srcPath: path + filename+'.big.jpg',
            dstPath: path + filename+'.jpg',
            width: 160,
            height: 160,
            quality: 0.8
        });

        console.log('uploadAvatar: resized');
        Meteor.users.update(this.userId, {
                $set: {
                    avatar: filename+'.jpg'
                }
            });
    }
});
```

**this cause error:**

``` javascript
uploadAvatar: wrinting... stef_1405792951
uploadAvatar: resizing...
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:998:11)
    at Process.ChildProcess._handle.onexit (child_process.js:789:34)
=> Exited with code: 8
```

**Comment by stefanocudini** [comment]
the problem is cause from missing dpkg package: imagemagick

```
aptitude install imagemagick
```

**Comment by stefanocudini** [comment]
@sylvaingi I think that this dependency should be specified in the Readme! ^ _ ^

**Comment by gauravchl** [comment]
Same error, but on windows 7, meteor 0.8.2
Any solution?
